env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64
  BASICS: yes
  CONFFLAGS_USR: -DKLH10_CTYIO_INT=0

task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  env:
    matrix:
      - EMULATOR: simh
      - EMULATOR: klh10
      - EMULATOR: pdp10-ka
        NODUMP: true
      # EMULATOR: pdp10-kl
  install_script: sh -ex build/dependencies.sh install_freebsd
  script: gmake its EMULATOR=$EMULATOR
