image: ubuntu

variables:
  EMULATOR: pdp10-ka

stages:
  - build

job1:
  stage: build
  script:
    - sh -ex build/dependencies.sh install_linux
    - make
  artifacts:
    paths:
      - out/pdp10-ka/
