<DEFINE VFLOAD (X) <FLOAD .X> <PRINTSTRING <STRING .X " loaded">> <TERPRI>>
<VFLOAD "prim.mud">
<VFLOAD "defs.mud">
<VFLOAD "makstr.mud">
<VFLOAD "tell-repl.mud">
<VFLOAD "act1.mud">
<VFLOAD "act2.mud">
<VFLOAD "act3.mud">
<VFLOAD "act4.mud">
;<VFLOAD "b.mud">
<VFLOAD "disp1.mud">
<VFLOAD "parser.mud">
<VFLOAD "melee.mud">
<VFLOAD "rooms.mud">
<VFLOAD "dung.mud">
<VFLOAD "impl.mud">
<VFLOAD "sr.mud">
<VFLOAD "syntax.mud">
<VFLOAD "typhak.mud">
<VFLOAD "util.mud">
