	TITLE LISP MACHINE CONSOLE PROGRAM LOADER

A=1
B=2
C=3
D=4
E=5
T=6
TT=7
P=17

TYICH=11
TYOCH=12

PDL:	-20,,.
	BLOCK 20

XJNAME:	0

GO:	MOVE P,PDL
	.OPEN TYICH,[.UAI,,'TTY]
	 .LOSE 1400
	.OPEN TYOCH,[.UAO,,'TTY]
	 .LOSE 1400
	.SUSET [.RXJNAME,,XJNAME]
	MOVE A,XJNAME
	CAME A,[SIXBIT/LISPM/]
	 CAMN A,[SIXBIT/CADR/]
	  CAIA
	   .VALUE [ASCIZ/: UNRECOGNIZED XJNAME î/]
	MOVE A,[SQUOZE 0,MAXJ]
	.EVAL A,
	 .LOSE
	SUBI A,1
FJ:	.CALL [	SETZ
		'USRVAR
		MOVEI %JSNUM(A)
		[SIXBIT/JNAME/]
		SETZM B ]
	 JRST FJ1
	CAMN B,XJNAME
	 JRST REOWNP
FJ1:	SOJG A,FJ
NEWJOB:	MOVE A,[SIXBIT/CADR/]
	CAME A,XJNAME
	 MOVE A,[SIXBIT/CC/]
	.CALL [	SETZ
		SIXBIT/OPEN/
		[.UII,,17]
		[SIXBIT/DSK/]
		[SIXBIT/TS/]
		A
		SETZ [SIXBIT/LISPM1/]]
	 JRST RELOAD
	CAMN A,[SIXBIT/CC/]
	 .VALUE [ASCIZ\ :LOADING PDUMPED VERSION 

:LOAD DSK:LISPM1;TS CC
:GOî\]
	 .VALUE [ASCIZ\ :LOADING PDUMPED VERSION 

:LOAD DSK:LISPM1;TS CADR
:GOî\]



RELOAD:	CAMN A,[SIXBIT/CC/]
	 .VALUE [ASCIZ\ :LOADING NEW VERSION FROM SCRATCH 

:LOAD SYS:TS LISP
:JCL LMCONS;CC (INIT)
:GOî\]
	 .VALUE [ASCIZ\ :LOADING NEW VERSION FROM SCRATCH 

:LOAD SYS:TS LISP
:JCL LMCONS;CCD (INIT)
:GOî\]

REOWNP:	.SUSET [.RUIND,,B]
	CAMN A,B
	 JRST FJ1		;robot
	.CALL [	SETZ
		'USRVAR
		MOVEI %JSNUM(A)
		[SIXBIT/APRC/]
		SETZM B ]
	 JRST FJ1
	JUMPL B,REOWN2
	.CALL [	SETZ
		'USRVAR
		MOVEI %JSNUM(A)
		[SIXBIT/UNAME/]
		SETZM TT ]
	 JRST FJ1
	PUSHJ P,SIXOUT
	MOVEI TT,[ASCIZ\ LISPM EXISTS AND ISN'T DISOWNED.  CONTINUE?\]
REOWN4:	PUSHJ P,ASZOUT
	PUSHJ P,YORN
	 .BREAK 16,160000
	JRST FJ1

REOWN2:	.CALL [	SETZ
		'USRVAR
		MOVEI %JSNUM(A)
		[SIXBIT/UNAME/]
		SETZM C ]
	 .LOSE 1000
	.CALL [	SETZ
		'USRVAR
		MOVEI %JSNUM(A)
		[SIXBIT/INTB/]
		SETZM TT ]
	 .LOSE 1000
	JUMPGE TT,REOWN3	;NOT TOP LEVEL
	MOVEI TT,[ASCIZ\REOWN \]
	PUSHJ P,ASZOUT
	MOVE TT,C
	PUSHJ P,SIXOUT
	.IOT TYOCH,[40]
	MOVE TT,XJNAME
	PUSHJ P,SIXOUT
	.IOT TYOCH,[77]
	PUSHJ P,YORN
	 JRST FJ1
	MOVE TT,[IDPB T,E]
	MOVEM TT,SIXOUI
	MOVE TT,C
	MOVE E,[260700,,BAR]
	PUSHJ P,SIXOUT
	MOVE E,[440700,,BAZ]
	MOVE TT,XJNAME
	PUSHJ P,SIXOUT
	.VALUE FOO

FOO:	ASCII\:KILL\
	ASCII\ :UJO\
BAR:	ASCII\B    \
	ASCII\     \
BAZ:	ASCIZ\LISPM  P\

REOWN3:	MOVE TT,C
	PUSHJ P,SIXOUT
	.IOT TYOCH,[40]
	MOVE TT,XJNAME
	PUSHJ P,SIXOUT
	MOVEI TT,[ASCIZ/ IS PART OF A DISOWNED TREE.  CONTINUE?/]
	JRST REOWN4

SIXOUT:	SETZ T,
	LSHC T,6
	ADDI T,40
SIXOUI:	.IOT TYOCH,T	;PATCHED TO IDPB
	JUMPN TT,SIXOUT
CPOPJ:	POPJ P,

ASZOUT:	HRLI TT,440700
ASZOU1:	ILDB T,TT
	JUMPE T,CPOPJ
	.IOT TYOCH,T
	JRST ASZOU1

YORN:	.IOT TYICH,TT
	.IOT TYOCH,[^M]
	CAIE TT,"Y
	 CAIN TT,"y
	  JRST POPJ1
	CAIE TT,"N
	 CAIN TT,"n
	  POPJ P,
	MOVEI TT,[ASCIZ\[Y OR N] \]
	PUSHJ P,ASZOUT
	JRST YORN

POPJ1:	AOS (P)
	POPJ P,

END GO
