Possible impending disaster: As some of you may know, the US Govt in its
finite wisdom has decided to stop supporting the Arpanet.  MIT's IMPs (the
packet-switching machines which heretofore have served as our connection to
the Arpanet) are expected to be turned off tomorrow.  Some efforts have
been made to replace the cross-country Arpanet functions by tying various
local-area nets together; such connections do exist for MIT.  However, we
can't guarantee how well this will work initially; we expect the new
connection system to require some time to undergo shakedown, and mail
service will probably go haywire during this period.  Please bear with us
in our time of trial.

Pandora Berman
for Postmaster@MC