name: Build Docker

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-docker:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        emulator: [klh10, simh, pdp10-ka, pdp10-kl, pdp10-ks]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build . --file build/docker/Dockerfile --build-arg EMULATOR=${{ matrix.emulator }} --tag ghcr.io/${GITHUB_REPOSITORY_OWNER@L}/its-${{ matrix.emulator }}:${{ github.sha }}
      - name: Push Docker image
        run: docker push ghcr.io/${GITHUB_REPOSITORY_OWNER@L}/its-${{ matrix.emulator }}:${{ github.sha }}
